name: Argo Deployment

on:
  push:
    tags:
      - wasfaty.release.**

jobs:
  DEV:
    environment: DEV
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "$SERVER_URL"

  QA:
    environment: QA
    needs: DEV
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"
  STG:
    environment: STG
    needs: QA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"
  PRD:
    environment: PRD
    needs: STG
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"