name: Argo Deployment

on:
  push:


jobs:
  DEV:
    environment: DEV
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          sed -i 's/SERVER_URL\=.*/LIST=https://api.wasfatyplus.com/' .env
          cat 

  QA:
    environment: QA
    needs: DEV
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"
  STG:
    environment: STG
    needs: QA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"
  PRD:
    environment: PRD
    needs: STG
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"