# ARGO Deployment
name: Argo Deployment

on:
  push:
    branches:  [main]


jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
  qa:
    runs-on: ubuntu-latest
    needs: dev
    environment: dev
    permissions:
      contents: read
      packages: write
  staging:
    runs-on: ubuntu-latest
    needs:   qa
    environment: dev
    permissions:
      contents: read
      packages: write
  production:
    runs-on: ubuntu-latest
    needs: staging
    environment: dev
    permissions:
      contents: read
      packages: write