name: Argo Deployment

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  DEV:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"

  QA:
    needs: DEV
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"
  STG:
    needs:   QA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"
  PRD:
    needs: STG
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build and push container
        run: |
          echo "test"